apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: back-end
  name: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: back-end
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: back-end
    spec:
      containers:
        - image: codecast/vidly-backend
          name: back-end
          ports:
            - containerPort: 3001
          resources: {}
      restartPolicy: Always
status: {}
