version: "3.9"
services:
  db:
    image: "mongo:4.0-xenial"
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
  backend: 
    depends_on: 
      - "db"
    build: ./backend
    ports: 
      - 3001:3001
    volumes:
      - ./backend:/app
    entrypoint: npm start
  frontend:
    depends_on: 
      - "backend"
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    entrypoint: yarn start 
volumes:
  vidly:
