version: "3.9"

services:
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

  backend: 
    depends_on: 
      - db
    build: ./backend
    image: vidly-backend 
    ports: 
      - 3001:3001
    volumes:
      - ./backend:/app
    environment: 
      DB_URL: mongodb://db/vidly
    entrypoint: ["sh", "./docker-entrypoint.sh"]

  backend-tests: 
    depends_on:
      - backend
    image: vidly-backend
    volumes:
      - ./backend:/app
    environment: 
      NODE_ENV: development
    entrypoint: npm run test:watch

  frontend:
    depends_on: 
      - backend
    build: ./frontend
    image: vidly-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment: 
      REACT_APP_API_URL: http://backend:3001/api
    entrypoint: yarn start 

  frontend-tests: 
    depends_on:
      - frontend
    image: vidly-frontend
    volumes:
      - ./frontend:/app
    # environment: 
    #   NODE_ENV: development
    entrypoint: npm test    

volumes:
  vidly:
