version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    # working_directory: ~/vidly-full
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: npm install --prefix backend 
      - run:
          name: Run backend tests
          command: npm test --prefix backend 
      - run:
          name: Install frontend dependencies
          command: npm install --prefix frontend 
      - run:
          name: Run frontend tests
          command: npm test --prefix frontend 
      - run:
          name: Run ls
          command: ls
      - run:
          name: Run pwd
          command: pwd
      - run: 
          name: SSH to DigitalOcean 
          command: ssh -oStrictHostKeyChecking=no root@143.198.21.26 "./deploy.sh"
      
      