version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout 
      - run:
          name: Echo Hello World
          command: echo hello world
      - run:
          name: ls
          command: ls
      