version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  first-workflow:
    jobs:
      backend:
        docker:
          - image: circleci/node
        steps:
          - checkout
          - run: cd web && npm install
          - run: cd web && npm test
