version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/vidly-full/backend 
    # environment:
    #   DB_URL: $DB_URL
    steps:
      - checkout:
          path: ~/vidly-full
      - run:
          name: Echo Hello World
          command: echo hello world
      - run:
          name: env
          command: env
      - run:
          name: pwd
          command: pwd
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      